# -*- coding: utf-8 -*-
"""Aprendizagem Supervisionada - Classificação.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OgGlbnFT-v1hlj4cenHz4cfjzcPU5d88

Prática 1 : **Exemplo** com Aprendizagem Supervisionada - CLASSIFICAÇÃO

**Link para a base de dados Diabetes:**  [Acesse aqui](https://www.kaggle.com/datasets/ehababoelnaga/diabetes-dataset)

"""
# INICIAL

# Imports

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Guardando os dados do CSV carregado em um Dataframe Pandas

base = pd.read_csv('Training.csv', sep=',')

# Linhas x Colunas

base.shape

# Mostrar a base de dados em si

base.head()

# Tipos de dados

base.dtypes

"""#**Tratamento dos Dados:**"""

# Mudar o nome das colunas

base = base.rename(columns={'Pregnancies' : 'Gestacoes', 'Glucose' : 'Glicose', 'BloodPressure' : 'PressaoArterial',
                            'SkinThickness' : 'EspessuraPele', 'Insulin' : 'Insulina', 'BMI' : 'IMC',
                            'DiabetesPedigreeFunction' : 'PedigreeDiabetes', 'Age' : 'Idade', 'Outcome' : 'Resultado'})

base.head()

# Verificando novamente os tipos de dados

base.info()

# Mostrando o numero de dados faltantes em cada coluna
base.isnull().sum()

# (Num tem)

base[['Glicose', 'Idade']].describe()

classes_diabete = base['Resultado'].valueCounts()
classes_diabete
# print(classes_diabete)

sns.countplot(x='Resultado', data=base)
plt.show()

# Gráfico de Pizza

nome_classes = ['Não tem diabetes', 'Tem diabetes']
quantidade_classes = [1500,960]
fig = plt.figure(figsize =(5, 5))
plt.pie(quantidade_classes, labels = nome_classes, autopct='%1.2f%%')
plt.show()

"""# Aprendizado de Máquina Supervisionado"""

# Importanto técnicas de avaliação de modelos de classificação
from sklearn.model_selection import train_test_split  #método de  particionamento dos dados em treino e teste
from sklearn.metrics import accuracy_score    # método para calcular a taxa de acerto
import numpy as np

# Importando as técnicas de aprendizagem (Classificadores)
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

#base_nova = base[['nome1','nome2','nome3','variavel saida']]

# Separação aleatória em conjuntos de treino e teste  (Treino = Para etapa de aprendizagem;  Teste = Para avaliar  o desempenho do modelo em novos dados)array = aprovacao_alunos.values
X = base[['Gestacoes',	'Glicose',	'PressaoArterial',	'EspessuraPele',	'Insulina',	'IMC', 'Idade']]   # X = variáveis explicativas
Y = base['Resultado']  # Y = variável resposta

np.random.seed(7)
X_treino, X_teste, Y_treino, Y_teste = train_test_split(X, Y, test_size=0.25) # Consideram treino 75% e teste 25%

# Arvore de Decisão
modelo1 = ArvoreDecisao()
modelo1.fit(X_treino, Y_treino)  #fit é o método para treinamento dos modelos

# SVM
modelo2 = SVM(kernel = "linear")
modelo2.fit(X_treino, Y_treino)

predicao1 = modelo1.predicao(X_teste)

print(predicao1)

print(Y_teste)

# Estimativas na base de teste (dados não vistos/futuros) = simulando o desempenho do modelo no mundo real
predicao1 = modelo1.predicao(X_teste)  # predict retorna a resposta dada pelo modelo
print("Taxa de Acerto com Arvore de Decisão = ", round((accuracy_score(Y_teste, predicao1)*100),2), "%")

predicao2 = modelo2.predicao(X_teste)
print("Taxa de Acerto com SVM = ", round((accuracy_score(Y_teste, predicao2)*100),2), "%")

pacientes = {
    'Gestacoes': [2, 7],
    'Glicose': [90, 133],
    'PressaoArterial': [68, 84],
    'EspessuraPele': [42,0],
    'Insulina': [0, 0],
    'IMC': [38.2, 40.2],
    'Idade': [27, 37]
}

df_pacientes = pd.DataFrame(pacientes)

print(df_pacientes)

predicoes = modelo1.predicao(df_pacientes)

for paciente in previsoes:
  if paciente == 1.0:
    print('O paciente ', int(paciente) + 1, ' possui alto risco de estar ou desenvolver diabetes')
  else:
    print( 'O paciente', int(paciente) + 1, ' não possui alto risco de desenvolver diabetes')

