# -*- coding: utf-8 -*-
"""Criação de um Data Storytelling com DS & ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iYIlCDvFAZGSGbDdsIOf40UWRgSgw_cO

## **Projeto FInal - Criação de um Data Storytelling com DS & ML**

**Chegadas de Turistas Internacionais:** Dados sobre a chegada de turistas internacionais não residentes ao Brasil

**Metadados:** Chegadas de turistas internacionais ao Brasil de 2015 à 2024.

**Descrição:** Reúne dados relativos ao número de chegadas de turistas internacionais ao Brasil, desagregados por países de residência permanente, meses e vias de acesso (aérea, terrestre, marítima ou fluvial).

**Fonte:** https://dados.turismo.gov.br/dataset/chegada-de-turistas-internacionais

**EQUIPE:** Cássio Santos, Danilo Melo, Georges Ballister, Kássio Fonseca, Romulo Galdino, Sara Lopes.
"""

from google.colab import drive
drive.mount('/content/drive')

# Importando bibliotecas.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import urllib

# Extração: Coletar dados de uma fonte.

# Lista de URLs dos arquivos CSV

urls = [
    "/content/drive/MyDrive/Colab Notebooks/Projeto Final/chegadas_2022.csv",
    "/content/drive/MyDrive/Colab Notebooks/Projeto Final/chegadas_2023.csv",
    "/content/drive/MyDrive/Colab Notebooks/Projeto Final/chegadas_2024.csv",
    "/content/drive/MyDrive/Colab Notebooks/Projeto Final/chegadas_2021.csv",
    "/content/drive/MyDrive/Colab Notebooks/Projeto Final/chegadas_2020.csv",
    "/content/drive/MyDrive/Colab Notebooks/Projeto Final/chegadas_2019.csv",
    "/content/drive/MyDrive/Colab Notebooks/Projeto Final/chegadas_2018.csv",
    "/content/drive/MyDrive/Colab Notebooks/Projeto Final/chegadas_2017.csv",
    "/content/drive/MyDrive/Colab Notebooks/Projeto Final/chegadas_2016.csv",
    "/content/drive/MyDrive/Colab Notebooks/Projeto Final/chegadas_2015.csv"
]
# Dicionário para renomear as colunas conforme o mapeamento desejado
mapeamento_colunas = {
    "Continente": "continenteDeorigem",
    "cod continente": "codContinente",
    "País": "paisDeOrigem",
    "cod pais": "codPais",
    "UF": "ufDestino",
    "cod uf": "codUf",
    "Via": "via",
    "cod via": "codVia",
    "ano": "ano",
    "Mês": "mes",
    "cod mes": "codMes",
    "Chegadas": "chegada"
}

# Lista para armazenar os DataFrames processados
lista_dfs = []

for url in urls:
    # Ler o CSV com o delimitador ';' e a codificação 'latin-1'
    df_temp = pd.read_csv(url, delimiter=';', encoding='latin-1')

    # Filtrar somente os registros onde a coluna "UF" é igual a "Pernambuco"
    df_temp = df_temp[df_temp["UF"] == "Pernambuco"]

    # Renomear as colunas conforme o mapeamento definido
    df_temp.rename(columns=mapeamento_colunas, inplace=True)

    # Adicionar o DataFrame processado à lista
    lista_dfs.append(df_temp)

# Concatenar todos os DataFrames da lista em um único DataFrame final
df_final = pd.concat(lista_dfs, ignore_index=True)

# Visualização inicial dos dados com os novos nomes de coluna
print("Visualização inicial dos dados:")
df_final.head() # Changed df to df_final

# Informações resumidas sobre o DataFrame
print('Informações do DataFrame:')
df_final.info()

"""#Implementação do modelo SARIMA

Análise exploratória dos dados

Visualizações para entender padrões sazonais

Decomposição da série temporal

Implementação do modelo SARIMA (modelo estatístico para tendência e sazonalidade)

Avaliação do modelo com métricas de desempenho

Previsão para todos os meses de 2025

Visualizações das previsões

# Importação de bibliotecas necessárias

Usamos essas métricas para avaliar a qualidade do nosso modelo de previsão
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from statsmodels.tsa.statespace.sarimax import SARIMAX
import warnings
warnings.filterwarnings('ignore')

"""#Agregação e Visualização da Série Temporal

Esta visualização inicial é essencial para entender o comportamento dos dados antes de aplicar qualquer modelo preditivo, ajudando a validar visualmente se o modelo de tendência e sazonalidade é adequado para este conjunto de dados.
"""

# Agregar dados por mês e ano para análise temporal
df_tempo = df_final.groupby(['ano', 'codMes'])['chegada'].sum().reset_index()
df_tempo['data'] = pd.to_datetime(df_tempo['ano'].astype(str) + '-' + df_tempo['codMes'].astype(str) + '-01')
df_tempo = df_tempo.sort_values('data')
df_tempo.set_index('data', inplace=True)

# Visualizar a série temporal
plt.figure(figsize=(14, 6))
plt.plot(df_tempo.index, df_tempo['chegada'], marker='o', linestyle='-')
plt.title('Chegadas de Turistas Internacionais em Pernambuco (2015-2024)', fontsize=14)
plt.xlabel('Ano', fontsize=12)
plt.ylabel('Número de Chegadas', fontsize=12)
plt.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""#Criação do Heatmap para Análise Sazonal

Este heatmap serve como uma ponte entre a análise estatística e o entendimento prático do comportamento do turismo em Pernambuco, facilitando tanto a modelagem técnica quanto a comunicação dos resultados.
"""

# Criar Heatmap para visualizar padrões sazonais
df_heatmap = df_tempo.reset_index()
df_heatmap['ano'] = df_heatmap['data'].dt.year
df_heatmap['mes'] = df_heatmap['data'].dt.month
pivot_table = df_heatmap.pivot_table(values='chegada', index='ano', columns='mes')


plt.figure(figsize=(14, 7))
ax = sns.heatmap(pivot_table, annot=True, fmt='.0f', cmap='YlGnBu', linewidths=0.5)
plt.title('Padrão Sazonal de Chegadas de Turistas por Mês e Ano', fontsize=14)
plt.xlabel('Mês', fontsize=12)
plt.ylabel('Ano', fontsize=12)
ax.set_xticklabels(['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'])
plt.tight_layout()
plt.show()

# Somar o total de chegadas nos últimos 10 anos
total_chegadas = df_final["chegada"].sum()
print(f"Total de chegadas nos últimos 10 anos: {total_chegadas}")

# Criar Heatmap para visualizar padrões sazonais em porcentagens
df_heatmap = df_tempo.reset_index()
df_heatmap['ano'] = df_heatmap['data'].dt.year
df_heatmap['mes'] = df_heatmap['data'].dt.month

# Calcular o total anual de chegadas
df_heatmap['total_ano'] = df_heatmap.groupby('ano')['chegada'].transform('sum')

# Calcular as porcentagens por mês
df_heatmap['percentual'] = (df_heatmap['chegada'] / df_heatmap['total_ano']) * 100

# Criar a tabela pivô com os valores de porcentagem
pivot_table = df_heatmap.pivot_table(values='percentual', index='ano', columns='mes')

# Plotar o heatmap
plt.figure(figsize=(14, 7))
ax = sns.heatmap(pivot_table, annot=True, fmt='.1f', cmap='YlGnBu', linewidths=0.5, cbar_kws={'label': 'Porcentagem (%)'})
plt.title('Padrão Sazonal de Chegadas de Turistas por Mês e Ano (em %)', fontsize=14)
plt.xlabel('Mês', fontsize=12)
plt.ylabel('Ano', fontsize=12)
ax.set_xticklabels(['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'])
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Supondo que 'df_final' já está carregado e contém os dados processados

# Somar as chegadas por país nos últimos 10 anos
df_aggregated = df_final.groupby("paisDeOrigem")["chegada"].sum().reset_index()

# Ordenar os países por número total de chegadas
df_aggregated = df_aggregated.sort_values(by="chegada", ascending=False)

# Selecionar os principais países por chegadas (top 10)
top_n = 20
df_top = df_aggregated.head(top_n)

# Criar o gráfico de barras
plt.figure(figsize=(12, 6))
plt.barh(df_top["paisDeOrigem"], df_top["chegada"], color='blue', edgecolor='black')
plt.xlabel("Número de Chegadas")
plt.ylabel("País de Origem")
plt.title("TOP 20 de Chegadas por País (Últimos 10 anos)")
plt.gca().invert_yaxis()  # Inverter para o país com mais chegadas ficar no topo
plt.show()

# Somar as chegadas por via de transporte
df_via = df_final.groupby("via")["chegada"].sum().reset_index()

# Unificar "Aérea" e "Aéreo"
aereo_total = df_via[df_via["via"].isin(["Aérea", "Aéreo"])]["chegada"].sum()
df_via = df_via[~df_via["via"].isin(["Aérea", "Aéreo"])]
df_via = pd.concat([df_via, pd.DataFrame([{"via": "Aéreo", "chegada": aereo_total}])], ignore_index=True)

# Unificar "Marítima" e "Marítimo"
maritimo_total = df_via[df_via["via"].isin(["Marítima", "Marítimo"])]["chegada"].sum()
df_via = df_via[~df_via["via"].isin(["Marítima", "Marítimo"])]
df_via = pd.concat([df_via, pd.DataFrame([{"via": "Marítimo", "chegada": maritimo_total}])], ignore_index=True)

# Recalcular a porcentagem
df_via["percentual"] = (df_via["chegada"] / df_via["chegada"].sum()) * 100

# Criar o gráfico de barras com porcentagens dentro
plt.figure(figsize=(10, 6))
bars = plt.bar(df_via["via"], df_via["chegada"], color='green', edgecolor='black')

# Adicionar porcentagens acima das barras
for bar, percent in zip(bars, df_via["percentual"]):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height(), f'{percent:.1f}%',
             ha='center', va='bottom', fontsize=12, fontweight='bold', color='black')

# Configurações do gráfico
plt.xlabel("Via de Transporte")
plt.ylabel("Número de Chegadas")
plt.title("Número/Porcentagem de Chegadas por Via (Últimos 10 anos)")
plt.show()

"""#Decomposição da Série Temporal

Esta análise de decomposição serve como ponte entre a análise exploratória inicial e a modelagem preditiva mais sofisticada com SARIMA, fornecendo uma base teórica para o modelo e uma forma visual de entender o comportamento do turismo em Pernambuco.

"""

# Decomposição da série temporal para analisar tendência e sazonalidade
from statsmodels.tsa.seasonal import seasonal_decompose

# Mudar o modelo para 'additive' se houver valores zero ou negativos
if (df_tempo['chegada'] <= 0).any():
    model = 'additive'
else:
    model = 'multiplicative'

# Realizar decomposição com o modelo selecionado
decomposicao = seasonal_decompose(df_tempo['chegada'], model=model, period=12)

# Visualizar a decomposição
plt.figure(figsize=(14, 12))

plt.subplot(411)
plt.plot(decomposicao.observed)
plt.title('Série Original', fontsize=12)
plt.grid(True, alpha=0.3)

plt.subplot(412)
plt.plot(decomposicao.trend)
plt.title('Tendência', fontsize=12)
plt.grid(True, alpha=0.3)

plt.subplot(413)
plt.plot(decomposicao.seasonal)
plt.title('Sazonalidade', fontsize=12)
plt.grid(True, alpha=0.3)

plt.subplot(414)
plt.plot(decomposicao.resid)
plt.title('Resíduos', fontsize=12)
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""#Teste de Estacionariedade e Implementação do Modelo SARIMA"""

# Preparar os dados para treinar o modelo

# Verificar estacionariedade
from statsmodels.tsa.stattools import adfuller

result = adfuller(df_tempo['chegada'])
print('\nTeste de Estacionariedade:')
print(f'Estatística do teste ADF: {result[0]}')
print(f'Valor-p: {result[1]}')
print(f'Valores críticos:')
for key, value in result[4].items():
    print(f'   {key}: {value}')

# Se o valor-p é maior que 0.05, não podemos rejeitar a hipótese nula, indicando que a série não é estacionária

# Implementar modelo SARIMA (Seasonal ARIMA) - uma implementação estatística do modelo de tendência e sazonalidade
print("\nTreinando o modelo SARIMA...")

# Definir parâmetros para o modelo
# (p, d, q) para a parte não sazonal
# (P, D, Q, s) para a parte sazonal
# s é o número de períodos em uma temporada (12 para dados mensais)
ordem = (1, 1, 1)
ordem_sazonal = (1, 1, 1, 12)

# Treinar o modelo
modelo = SARIMAX(df_tempo['chegada'],
                order=ordem,
                seasonal_order=ordem_sazonal,
                enforce_stationarity=False,
                enforce_invertibility=False)

resultado_modelo = modelo.fit(disp=False)

# Exibir resumo do modelo
print(resultado_modelo.summary())

# Fazer previsões dentro da amostra (in-sample)
previsoes_dentro = resultado_modelo.get_prediction(dynamic=False)
previsoes_df = previsoes_dentro.predicted_mean
erros_padrao = previsoes_dentro.se_mean

# Visualizar as previsões dentro da amostra
plt.figure(figsize=(14, 6))
plt.plot(df_tempo.index, df_tempo['chegada'], 'b-', label='Dados Reais')
plt.plot(previsoes_df.index, previsoes_df, 'r--', label='Previsões')
plt.fill_between(previsoes_df.index,
                previsoes_df - 1.96 * erros_padrao,
                previsoes_df + 1.96 * erros_padrao,
                color='pink', alpha=0.3, label='Intervalo de Confiança 95%')
plt.title('Previsões vs Valores Reais (Dentro da Amostra)', fontsize=14)
plt.legend(loc='best')
plt.xlabel('Ano')
plt.ylabel('Número de Chegadas')
plt.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Calcular métricas de erro para as previsões dentro da amostra
y_true = df_tempo['chegada']
y_pred = previsoes_df

rmse = np.sqrt(mean_squared_error(y_true, y_pred))
mae = mean_absolute_error(y_true, y_pred)
r2 = r2_score(y_true, y_pred)
mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
accuracy = 100 - mape

print('\nMétricas de Desempenho do Modelo')
print(f'RMSE (Erro Quadrático Médio da Raiz): {rmse:.2f}')
print(f'MAE (Erro Absoluto Médio): {mae:.2f}')
print(f'R² (Coeficiente de Determinação): {r2:.4f}')
print(f'MAPE (Erro Percentual Absoluto Médio): {mape:.2f}%')
print(f'Acurácia: {accuracy:.2f}%')

"""#Previsões de chegada de turistas para 2025"""

# Fazer previsões para 2025 (próximos 12 meses)
steps = 12  # número de meses em 2025
previsoes_futuro = resultado_modelo.forecast(steps=steps)

# Criar um dataframe para as previsões
datas_2025 = pd.date_range(start=df_tempo.index[-1] + pd.DateOffset(months=1),
                          periods=steps, freq='MS')
df_previsoes = pd.DataFrame({
    'data': datas_2025,
    'chegada_prevista': np.round(previsoes_futuro).astype(int)
})

# Exibir as previsões para 2025
print('\nPrevisões de Chegadas de Turistas para 2025:')
df_previsoes['mes'] = df_previsoes['data'].dt.month
df_previsoes['ano'] = df_previsoes['data'].dt.year
df_previsoes_display = df_previsoes[['ano', 'mes', 'chegada_prevista']]
print(df_previsoes_display)

# Visualizar previsões para 2025
plt.figure(figsize=(14, 6))

# Dados históricos
plt.plot(df_tempo.index, df_tempo['chegada'], 'b-', marker='o', markersize=5, label='Dados Históricos')

# Previsões
plt.plot(df_previsoes['data'], df_previsoes['chegada_prevista'], 'r--', marker='o', markersize=5, label='Previsões 2025')

plt.title('Previsão de Chegadas de Turistas Internacionais a Pernambuco para 2025', fontsize=14)
plt.xlabel('Ano', fontsize=12)
plt.ylabel('Número de Chegadas', fontsize=12)
plt.axvline(x=df_tempo.index[-1], color='gray', linestyle='--', alpha=0.8, label='Início das Previsões')
plt.legend(loc='best')
plt.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Gerar gráfico de barras para visualizar as previsões mensais para 2025
plt.figure(figsize=(14, 6))
bars = plt.bar(range(1, 13), df_previsoes['chegada_prevista'], color='skyblue')
plt.xlabel('Mês', fontsize=12)
plt.ylabel('Chegadas Previstas', fontsize=12)
plt.title('Previsão Mensal de Chegadas de Turistas Internacionais a Pernambuco em 2025', fontsize=14)
plt.xticks(range(1, 13), ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'])
plt.grid(axis='y', alpha=0.3)

# Adicionar os valores no topo das barras
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height + 50,
            f'{int(height)}', ha='center', va='bottom', fontsize=10)

plt.tight_layout()
plt.show()

# Salvar as previsões em um arquivo CSV
df_previsoes.to_csv('previsoes_chegadas_pernambuco_2025.csv', index=False)
print("\nPrevisões salvas no arquivo 'previsoes_chegadas_pernambuco_2025.csv'")

# Exportar o modelo treinado para uso futuro (opcional)
import pickle

with open('modelo_previsao_turismo_pernambuco.pkl', 'wb') as arquivo:
    pickle.dump(resultado_modelo, arquivo)
print("Modelo salvo como 'modelo_previsao_turismo_pernambuco.pkl'")