# -*- coding: utf-8 -*-
"""Data Storytelling: Análise de Falecimentos entre Estudantes em Recife.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GbGU31lSKOYgHkCaByjK-gbpI0_HAciu

# Projeto de Data Storytelling: Análise de Falecimentos entre Estudantes em Recife (2024)
## Contextualização
Este projeto visa investigar os casos de falecimento entre estudantes no Recife em 2024, identificando grupos de risco, localidades mais afetadas e características que podem subsidiar intervenções públicas.

Alunos: Cássio Santos, Georges Ballister, Kássio Fonseca, Danilo Melo, Romulo Galdino e Sara Lopes

## 1. Coleta e Análise Inicial dos Dados
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Carregamento dos dados
url_csv = "http://dados.recife.pe.gov.br/dataset/ce5168d4-d925-48f5-a193-03d4e0f587c7/resource/96f8a467-12b1-4340-b19c-281907fabaae/download/situacaofinal2024.csv"
df = pd.read_csv(url_csv, delimiter=';')
df.head()

"""### Exploração Inicial dos Dados"""

# Informações gerais sobre os dados
df.info()

# Verificar valores nulos e estatísticas gerais
print("Valores nulos por coluna:\n", df.isnull().sum())
df.describe(include='all')

"""### Analisando a Distribuição Etária dos Falecidos

Inicialmente, vamos entender a faixa etária mais vulnerável entre os estudantes falecidos em Recife.  
Essa análise ajuda a direcionar ações preventivas e políticas públicas específicas para grupos de maior risco.

## 2. Pré-processamento dos Dados
"""

# Padronizar nomes das colunas para minúsculo
df.columns = df.columns.str.lower()

# Analisar valores únicos na situação dos alunos
df['situacao_nome'].value_counts()

"""### Identificando as Áreas de Maior Risco

Após observar a faixa etária mais afetada, buscamos entender quais são os bairros com maior incidência de casos. Essa análise geográfica permitirá ações mais direcionadas, melhorando a eficiência de medidas preventivas.

## 2. Análises e Visualizações

### Distribuição Etária dos Estudantes Falecidos

### Analisando um Caso Específico: COHAB

Selecionamos o bairro COHAB para uma análise aprofundada devido ao alto número de casos observados.  
Investigaremos aqui se há diferenças importantes relacionadas à idade e ao sexo nas escolas desse bairro.

### Avaliando o Impacto Relativo

Por fim, além dos números absolutos, é fundamental entender o impacto proporcional das mortes em relação à população estudantil total de cada bairro. Isso nos dará uma visão mais clara das áreas mais severamente afetadas e que talvez precisem de intervenções mais urgentes.
"""

# Filtrar estudantes falecidos
df_falecidos = df[df['situacao_nome'].str.contains('falecido', case=False, na=False)]

# Distribuição das idades
plt.figure(figsize=(8, 6))
sns.histplot(df_falecidos['idade'], bins=10, kde=True)
plt.title('Distribuição Etária dos Estudantes Falecidos em Recife (2024)')
plt.xlabel('Idade')
plt.ylabel('Número de Casos')
plt.show()

"""### Ranking dos Bairros com Maior Número de Falecimentos"""

# Agrupar mortes por bairro
mortes_por_bairro = df[df['situacao_nome'].str.contains('falecido', case=False, na=False)]                     .groupby('endereco_bairro').size().sort_values(ascending=False)

# Gráfico
plt.figure(figsize=(12, 8))
sns.barplot(x=mortes_por_bairro.values, y=mortes_por_bairro.index, palette='viridis')
plt.title('Ranking dos Bairros com Maior Número de Falecimentos')
plt.xlabel('Número de Mortes')
plt.ylabel('Bairro')
plt.show()

"""### Análise Detalhada por Bairro: Caso da COHAB"""

# Filtrar registros de falecidos no bairro "cohab"
df_falecidos_cohab = df[
    (df['situacao_nome'].str.contains('falecido', case=False, na=False)) &
    (df['endereco_bairro'].str.contains('cohab', case=False, na=False))
]

# Ajuste opcional: se a coluna 'sexo' estiver codificada numericamente, você pode convertê-la para rótulos:
# Exemplo: 1 -> 'Masculino', 2 -> 'Feminino'
df_falecidos_cohab['sexo'] = df_falecidos_cohab['sexo'].replace({1: 'Masculino', 2: 'Feminino'})

# Configurar o tamanho da figura para acomodar as escolas no eixo X
plt.figure(figsize=(14, 8))

# Criar o boxplot: cada escola terá uma caixa para cada sexo (diferenciado por cor)
sns.boxplot(x='escola', y='idade', hue='sexo', data=df_falecidos_cohab, showfliers=False)

# Sobrepor os pontos individuais com um swarm plot para visualizar os dados brutos
#sns.swarmplot(x='escola', y='idade', hue='sexo', data=df_falecidos_cohab, dodge=True, color='black', alpha=0.6)
sns.swarmplot(x='escola', y='idade', hue='sexo', data=df_falecidos_cohab, dodge=True)

# Remover a duplicidade da legenda (pois o hue foi usado duas vezes)
handles, labels = plt.gca().get_legend_handles_labels()
# Assumindo que os dois primeiros grupos são iguais, pegamos apenas os da primeira plotagem
n = len(set(df_falecidos_cohab['sexo']))
plt.legend(handles[:n], labels[:n], title='Sexo')

plt.title('Distribuição de Idade dos Falecidos no Bairro COHAB\npor Escola e Sexo')
plt.xlabel('Escola')
plt.ylabel('Idade')
#plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### Impacto Relativo dos Falecimentos por Bairro"""

# 1. Identificar os bairros que possuem registros de falecimento
bairros_com_falecido = df[df['situacao_nome'].str.contains('falecido', case=False, na=False)]['endereco_bairro'].unique()

# 2. Filtrar o DataFrame para considerar apenas os alunos dos bairros identificados (população total desses bairros)
df_pop_bairros = df[df['endereco_bairro'].isin(bairros_com_falecido)]

# 3. Calcular o total de alunos (matrículas) por bairro
total_alunos = df_pop_bairros.groupby('endereco_bairro')['matricula'].count()

# 4. Calcular o número de falecidos por bairro
falecidos = df[df['situacao_nome'].str.contains('falecido', case=False, na=False)] \
             .groupby('endereco_bairro')['matricula'].count()

# 5. Criar um DataFrame com o total, os falecidos e a porcentagem
df_percent = pd.DataFrame({
    'Total': total_alunos,
    'Falecidos': falecidos
})
df_percent['Falecidos'] = df_percent['Falecidos'].fillna(0)  # Caso algum bairro não tenha falecidos
df_percent['Porcentagem'] = (df_percent['Falecidos'] / df_percent['Total']) * 100

# Ordenar por porcentagem (de forma decrescente) para facilitar a visualização
df_percent = df_percent.sort_values('Porcentagem', ascending=False)

# 6. Criar o gráfico de barras horizontais
plt.figure(figsize=(12, 8))
ax = sns.barplot(x=df_percent['Porcentagem'], y=df_percent.index, palette='viridis')
plt.title('Porcentagem de Falecidos sobre a População de Alunos por Bairro')
plt.xlabel('Porcentagem de Falecidos (%)')
plt.ylabel('Bairro')

# Adicionar anotações com a porcentagem em cada barra
for i, v in enumerate(df_percent['Porcentagem']):
    ax.text(v, i, f"{v:.1f}%", color='white', va='center', ha='right', fontweight='bold')
plt.xlim(0, df_percent['Porcentagem'].max() + 0.05)

plt.show()

"""## 3. Conclusões e Recomendações

### Principais Insights
- A faixa etária predominante aponta para vulnerabilidades específicas em certas idades.
- Bairros como COHAB apresentam maior concentração e exigem atenção prioritária.

### Recomendações
- Fortalecer políticas públicas educacionais e de saúde nas áreas críticas identificadas.
- Desenvolver estudos qualitativos adicionais para compreender causas subjacentes às taxas observadas.
- Realizar campanhas específicas nas escolas mais afetadas.
"""