# -*- coding: utf-8 -*-
"""Machine Learning - Desafio 1 - Classificação.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-d8Rhfcyr2BNKqfsbvbuD1iFJjljfLa

#**📝 Orientações para a atividade:**

* Use o dataset como referência;  
* Construa modelos;  
* Justifique suas escolhas e gere comparações.  

`Alunos: Cássio Santos e Sara Lopes.`

## **✨Imports, limpeza e análise exploratória dos dados:**
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay, roc_curve, roc_auc_score, accuracy_score
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
import seaborn as sns
import random

df = pd.read_csv('/content/dataset_agrario_pratica.csv')

df.head()

print(df.isnull().sum())

df.shape

# Variáveis categóricas
cat_cols = ['Cultura', 'Região', 'Tipo de Solo', 'Tipo de Irrigação', 'Tipo de Fertilizante']
num_cols = ['Área (ha)', 'Produtividade (sacas/ha)']

# Separar X e y
X = df.drop('Status de Produção', axis=1)
y = df['Status de Produção']

# Separar treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.3)

# Pré-processamento com OneHotEncoder
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ],
    remainder='passthrough'
)

# Visulização dos DFs gerados:
X.head()
y.head()

y.shape

"""## **🤖 Modelos testados:**

### **😠 Regressão Logística**
"""

pipe_lr = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000))
])

pipe_lr.fit(X_train, y_train)
y_pred_lr = pipe_lr.predict(X_test)
print("Logistic Regression:\n", classification_report(y_test, y_pred_lr))

pred = pipe_lr.predict(X)
print(f'Previsão:  {pred[0]}')

y_real = df['Status de Produção'].values  # verdadeiro, extraído do dataframe original

# Ver relatório de desempenho
print("Acurácia:", accuracy_score(y_real, pred))
print("\nRelatório completo:\n", classification_report(y_real, pred))

# Matriz de confusão
cm = confusion_matrix(y_real, pred, labels=["Alta", "Baixa"])
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Alta", "Baixa"])
disp.plot()



"""### **🌳 Random Forest**"""

pipe_rf = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier())
])

pipe_rf.fit(X_train, y_train)
y_pred_rf = pipe_rf.predict(X_test)
print("Random Forest:\n", classification_report(y_test, y_pred_rf))

pred = pipe_rf.predict(X)
print(f'Previsão: {pred[0]}')

y_real = df['Status de Produção'].values  # verdadeiro, extraído do dataframe original

# Ver relatório de desempenho
print("Acurácia:", accuracy_score(y_real, pred))
print("\nRelatório completo:\n", classification_report(y_real, pred))

# Matriz de confusão
cm = confusion_matrix(y_real, pred, labels=["Alta", "Baixa"])
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Alta", "Baixa"])
disp.plot()

"""✅ Justificativas das escolhas
OneHotEncoder: transforma variáveis categóricas em vetores numéricos binários.

Logistic Regression: modelo simples e interpretável, bom ponto de partida.

Random Forest: funciona bem com dados mistos, lida com não linearidades e interações automaticamente.

Train/Test Split estratificado: garante que a proporção de classes seja mantida.

## **😎 Exemplos de Cross-validation:**
"""

# Avaliando com acurácia
scores = cross_val_score(pipe_rf, X, y, cv=5, scoring='accuracy')

print("Acurácias em cada fold:", scores)
print("Acurácia média:", scores.mean())
print("Desvio padrão:", scores.std())

# F1-score
f1_scores = cross_val_score(pipe_rf, X, y, cv=5, scoring='f1_macro')
print("F1-score médio (macro):", f1_scores.mean())

# F1-score
f1_scores = cross_val_score(pipe_rf, X, y, cv=5, scoring='f1_weighted')
print("F1-score médio (macro):", f1_scores.mean())

acc_rf = cross_val_score(pipe_rf, X, y, cv=5, scoring='accuracy')
acc_lr = cross_val_score(pipe_lr, X, y, cv=5, scoring='accuracy')

print("Random Forest - Média:", acc_rf.mean())
print("Logistic Regression - Média:", acc_lr.mean())

# Coleta dos scores
scores_rf = cross_val_score(pipe_rf, X, y, cv=5, scoring='accuracy')
scores_lr = cross_val_score(pipe_lr, X, y, cv=5, scoring='accuracy')

# Preparar dados para o boxplot
data = {
    'Random Forest': scores_rf,
    'Logistic Regression': scores_lr
}

df_plot = pd.DataFrame(data)

# Gráfico
plt.figure(figsize=(8, 5))
sns.boxplot(data=df_plot, palette='Set2')
plt.ylabel('Acurácia')
plt.title('Comparação de Acurácia - Cross Validation (5 folds)')
plt.grid(True)
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Previsões de cada modelo
y_pred_lr = pipe_lr.predict(X)
y_pred_rf = pipe_rf.predict(X)

# Classes (para garantir ordem correta)
labels = ["Alta", "Baixa"]

# Matrizes
cm_lr = confusion_matrix(y, y_pred_lr, labels=labels)
cm_rf = confusion_matrix(y, y_pred_rf, labels=labels)

# Plotando lado a lado
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Logistic Regression
disp_lr = ConfusionMatrixDisplay(confusion_matrix=cm_lr, display_labels=labels)
disp_lr.plot(ax=axes[0], cmap='Blues', values_format='d')
axes[0].set_title("Matriz - Regressão Logística")

# Random Forest
disp_rf = ConfusionMatrixDisplay(confusion_matrix=cm_rf, display_labels=labels)
disp_rf.plot(ax=axes[1], cmap='Greens', values_format='d')
axes[1].set_title("Matriz - Random Forest")

plt.tight_layout()
plt.show()

"""## **🎯 Testagem Com Base de Dados Fictícios:**

Pedimos ao chatGPT para gerar um arquivo com dados fictícios que tivesse o ***status de produtividade*** condizente com o nosso modelo de previsão. Esse foi o resultado:
"""

dfTeste = pd.read_csv('/content/base_agricola_500_linhas.csv')

dfTeste.head()

# Separar X
TesteReal = dfTeste.drop('Status de Produção', axis=1)

pred = pipe_lr.predict(TesteReal)
print(f'Previsão:  {pred[0]}')

y_real = dfTeste['Status de Produção'].values  # verdadeiro, extraído do dataframe original

# Ver relatório de desempenho
print("Acurácia:", accuracy_score(y_real, pred))
print("\nRelatório completo:\n", classification_report(y_real, pred))

# Matriz de confusão
cm = confusion_matrix(y_real, pred, labels=["Alta", "Baixa"])
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Alta", "Baixa"])
disp.plot()

# Separar X
TesteReal = dfTeste.drop('Status de Produção', axis=1)

pred = pipe_rf.predict(TesteReal)
print(f'Previsão:  {pred[0]}')

y_real = dfTeste['Status de Produção'].values  # verdadeiro, extraído do dataframe original

# Ver relatório de desempenho
print("Acurácia:", accuracy_score(y_real, pred))
print("\nRelatório completo:\n", classification_report(y_real, pred))

# Matriz de confusão
cm = confusion_matrix(y_real, pred, labels=["Alta", "Baixa"])
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Alta", "Baixa"])
disp.plot()

"""## 👀 Por questões de curiosidade:"""

# Definições de valores possíveis para cada coluna categórica
culturas = ["Arroz", "Milho", "Café", "Trigo", "Soja"]
regioes = ["Norte", "Nordeste", "Centro-Oeste", "Sudeste", "Sul"]
tipos_solo = ["Argiloso", "Arenoso", "Misto", "Siltoso"]
tipos_irrigacao = ["Irrigado", "Seca"]
tipos_fertilizante = ["Químico", "Orgânico", "Nenhum"]

# Função para simular produtividade baseada em características
def gerar_produtividade(cultura, irrigacao, fertilizante):
    base = random.uniform(30, 100)
    if irrigacao == "Seca":
        base -= random.uniform(10, 30)
    if fertilizante == "Nenhum":
        base -= random.uniform(5, 15)
    elif fertilizante == "Orgânico":
        base += random.uniform(0, 5)
    else:
        base += random.uniform(5, 10)
    return round(max(10, min(base, 100)), 2)

# Função para definir status de produção baseado na produtividade
def definir_status(produtividade):
    return "Alta" if produtividade >= 70 else "Baixa"

# Gerar os dados sintéticos
random.seed(42)
np.random.seed(42)
linhas = 5000000
dados = []

for _ in range(linhas):
    cultura = random.choice(culturas)
    regiao = random.choice(regioes)
    solo = random.choice(tipos_solo)
    irrigacao = random.choice(tipos_irrigacao)
    fertilizante = random.choice(tipos_fertilizante)
    area = round(random.uniform(1, 100), 2)
    produtividade = gerar_produtividade(cultura, irrigacao, fertilizante)
    status = definir_status(produtividade)
    dados.append([cultura, regiao, solo, irrigacao, fertilizante, area, produtividade, status])

# Criar o DataFrame
df = pd.DataFrame(dados, columns=[
    "Cultura", "Região", "Tipo de Solo", "Tipo de Irrigação", "Tipo de Fertilizante",
    "Área (ha)", "Produtividade (sacas/ha)", "Status de Produção"
])

# Salvar como CSV
caminho_arquivo = "/content/base_agricola_5000000_linhas.csv"
df.to_csv(caminho_arquivo, index=False)
caminho_arquivo

dfTeste = pd.read_csv('/content/base_agricola_5000000_linhas.csv')

# Separar X
TesteReal = dfTeste.drop('Status de Produção', axis=1)

pred = pipe_lr.predict(TesteReal)
print(f'Previsão:  {pred[0]}')

# Geração da matriz
cm = confusion_matrix(y_real, pred, labels=["Alta", "Baixa"])

# Exibição com formatação corrigida
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Alta", "Baixa"])
fig, ax = plt.subplots(figsize=(6, 6))  # Aumenta tamanho se quiser
disp.plot(ax=ax, cmap='viridis', values_format=',')  # vírgula adiciona separador de milhar
plt.title("Matriz de Confusão - Números Inteiros Formatados")
plt.show()

# Separar X
TesteReal = dfTeste.drop('Status de Produção', axis=1)

pred = pipe_rf.predict(TesteReal)
print(f'Previsão:  {pred[0]}')

y_real = dfTeste['Status de Produção'].values  # verdadeiro, extraído do dataframe original

# Geração da matriz
cm = confusion_matrix(y_real, pred, labels=["Alta", "Baixa"])

# Exibição com formatação corrigida
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Alta", "Baixa"])
fig, ax = plt.subplots(figsize=(6, 6))  # Aumenta tamanho se quiser
disp.plot(ax=ax, cmap='viridis', values_format=',')  # vírgula adiciona separador de milhar
plt.title("Matriz de Confusão - Números Inteiros Formatados")
plt.show()