# -*- coding: utf-8 -*-
"""ML para prever fraudes em transações em cartão de crédito.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gE-DwjhlFTjc0jskyCMST5Pt-bK5uMOj

# Modelo de machine learning para prever fraudes em transações em cartão de crédito

Alunos:

* Cássio Santos e Sara Lopes.

## Vamos seguir um processo estruturado para criar um modelo de previsão de fraudes em transações com cartão de crédito. O fluxo envolve:

* Analisar e entender a estrutura da base de dados.  
* Pré-processar e tratar os dados.  
* Realizar uma análise exploratória básica.
* Escolher e treinar um modelo preditivo.
* Avaliar o modelo e sugerir melhorias.

### Importações:
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
from collections import Counter
from imblearn.under_sampling import RandomUnderSampler
import xgboost as xgb
from sklearn.svm import SVC

dataset = pd.read_csv("/content/credit_card_fraud_dataset.csv", delimiter=",")

"""### 1 - Analisar e entender a estrutura da base de dados."""

dataset.shape

dataset.head()

df_head = dataset.head()
df_info = dataset.info()

df_head, df_info

target = dataset["IsFraud"].value_counts()
target

sns.set_style("whitegrid")

# Contagem de fraudes vs. não fraudes:
plt.figure(figsize=(6, 4))
columns = sns.countplot(x=dataset["IsFraud"], palette=["#00A6A6", "#6A0DAD"])
plt.xticks([0, 1], ["Legítima", "Fraude"])
plt.xlabel("Categoria")
plt.ylabel("Contagem")
plt.title("Distribuição de transações legítimas e fraudulentas")
plt.show()

# Ó se eu quisesse:
# Adicionar os valores exatos em cima das colunas:
for p in columns.patches:
    columns.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width() / 2, p.get_height()),
                ha='center', va='bottom', fontsize=12, fontweight='bold')

plt.figure(figsize=(8, 4))
sns.countplot(y=dataset["MerchantType"], hue=dataset["IsFraud"], palette=["#00A6A6", "#6A0DAD"])
plt.xlabel("Contagem")
plt.ylabel("Tipo de Comerciante")
plt.title("Distribuição de fraudes por tipo de comerciante")
plt.legend(["Legítima", "Fraude"])
plt.show()

plt.figure(figsize=(8, 4))
sns.countplot(y=dataset["DeviceType"], hue=dataset["IsFraud"], palette=["#00A6A6", "#6A0DAD"])
plt.xlabel("Contagem")
plt.ylabel("Tipo de Dispositivo")
plt.title("Distribuição de fraudes por tipo de dispositivo")
plt.legend(["Legítima", "Fraude"])
plt.show()

"""### 2 - Pré-processar e tratar os dados

Transformando variáveis categóricas em númericas para processamento de ML:
"""

# Criação de uma cópia dos dados originais para pré-processamento
df_processed = dataset.copy()

# Codificação das variáveis categóricas
categorical_columns = ['Location', 'MerchantType', 'DeviceType']
label_encoders = {}

for column in categorical_columns:
    le = LabelEncoder()
    df_processed[column] = le.fit_transform(df_processed[column])
    label_encoders[column] = le

# Remoção da coluna TransactionID (não útil para previsão)
df_processed.drop(['TransactionID'], axis=1, inplace=True)

# Padronização das variáveis numéricas
numeric_columns = ['Amount', 'Time', 'PreviousTransactions']
scaler = StandardScaler()
df_processed[numeric_columns] = scaler.fit_transform(df_processed[numeric_columns])

# Exibição dos dados processados
df_processed.head(10)

"""### 3 - Realizar uma análise exploratória básica"""

# Análise das variáveis categóricas categorizadas por fraude
categorical_columns = ['Location', 'MerchantType', 'DeviceType']

for column in categorical_columns:
    plt.figure(figsize=(10,5))
    sns.countplot(x=column, hue='IsFraud', data=df_processed, palette=["#00A6A6", "#6A0DAD"])
    plt.title(f'Distribuição de {column} por Fraude')
    plt.xlabel(column)
    plt.ylabel('Quantidade')
    plt.xticks(rotation=45)
    plt.legend(["Legítima", "Fraude"])
    plt.show()

# Boxplot para detecção de outliers em variáveis numéricas
for column in numeric_columns:
    plt.figure(figsize=(8,4))
    sns.boxplot(x='IsFraud', y=column, data=df_processed, hue='IsFraud', palette=["#00A6A6", "#6A0DAD"])
    plt.title(f'Boxplot de {column} por Fraude')
    plt.xlabel('Fraude (0=Não, 1=Sim)')
    plt.ylabel(column)
    plt.show()

# Matriz de correlação
plt.figure(figsize=(10,8))
sns.heatmap(df_processed.corr(), annot=True, cmap='coolwarm')
plt.title('Matriz de Correlação entre as variáveis')
plt.show()

"""### 4 - Escolher e treinar Alguns modelos preditivos

#### Trabalhando com Decision Forest:
"""

df_decisionTree = df_processed.copy()

df_decisionTree.head()

# Dividir os Dados em Treino e Teste

X = df_decisionTree.drop('IsFraud', axis=1)  # Excluindo a coluna target
y = df_decisionTree['IsFraud']  # Target

# Dividir em treino (80%) e teste (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Instanciar o classificador de árvore de decisão
dt_classifier = DecisionTreeClassifier(random_state=42)

# Treinar o modelo
dt_classifier.fit(X_train, y_train)

plt.figure(figsize=(30, 15))
plot_tree(dt_classifier, filled=True, feature_names=X.columns, class_names=['Non-Fraud', 'Fraud'], rounded=True, fontsize=10)
plt.show()

# Fazer previsões no conjunto de teste
y_pred = dt_classifier.predict(X_test)

# Acurácia
accuracy = accuracy_score(y_test, y_pred)
print(f'Acurácia: {accuracy:.4f}')

# Relatório de classificação
print(classification_report(y_test, y_pred))

# Matriz de confusão
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

"""**Conclusão:**


1. Acurácia: 0.85
Embora a acurácia pareça razoável (85%), ela esconde o fato de que o modelo não está detectando fraudes (classe 1). A acurácia está sendo mantida alta por causa da alta performance na classe 0 (não fraude).
2. Matriz de Confusão:
  * Classe 0 (Não fraude): O modelo classificou corretamente 17 exemplos como não fraudulentos, mas errou 3 exemplos como não fraudulentos (falsos negativos).

  * Classe 1 (Fraude): O modelo não detectou nenhuma fraude. Ou seja, o número de falsos negativos é 0, mas isso é porque o modelo nunca previu a classe fraude (1). Todos os exemplos fraudulentos foram classificados como não fraudulentos (0).

O modelo está falhando em identificar fraudes (classe 1), que é o objetivo principal. Ele está classificando todas as transações como não fraudulentas (classe 0).
"""

# Ajuste de Hiperparâmetros

# Definir a grade de parâmetros
param_grid = {
    'max_depth': [5, 10, 15, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Realizar a busca em grade
grid_search = GridSearchCV(estimator=dt_classifier, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)

# Treinar o modelo
grid_search.fit(X_train, y_train)

# Melhor modelo encontrado
print(f'Melhores parâmetros: {grid_search.best_params_}')

# Instanciar o classificador de árvore de decisão com os melhores parâmetros encontrados
best_dt_classifier = DecisionTreeClassifier(
    max_depth=5,
    min_samples_split=5,
    min_samples_leaf=1,
    random_state=42
)

# Treinar o modelo
best_dt_classifier.fit(X_train, y_train)

plt.figure(figsize=(30, 15))
plot_tree(best_dt_classifier, filled=True, feature_names=X.columns, class_names=['Non-Fraud', 'Fraud'], rounded=True, fontsize=10)
plt.show()

# Fazer previsões no conjunto de teste
y_pred = best_dt_classifier.predict(X_test)

# Avaliar o modelo
accuracy = accuracy_score(y_test, y_pred)
print(f'Acurácia: {accuracy:.4f}')

# Relatório de classificação
print(classification_report(y_test, y_pred))

# Matriz de confusão
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

"""Desbalanceamento de classes: A classe "fraude" (classe 1) pode ser muito menor em comparação com a classe "não fraude" (classe 0). Isso pode fazer com que a árvore de decisão "ignore" as fraudes, já que ela está priorizando a acurácia geral, e classificar tudo como não fraude.

Overfitting ou underfitting: Embora o ajuste de hiperparâmetros tenha ajudado a melhorar a acurácia, a árvore ainda pode estar muito simples para capturar as complexidades da classe fraudulenta. O modelo pode estar subajustando (underfitting).

#### Treinando o Random Forest:
"""

# Treinar o modelo Random Forest
rf_classifier = RandomForestClassifier(random_state=42, class_weight='balanced')
rf_classifier.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred_rf = rf_classifier.predict(X_test)

# Avaliar o modelo
accuracy = accuracy_score(y_test, y_pred_rf)
print(f'Acurácia: {accuracy:.4f}')

# Relatório de classificação
print(classification_report(y_test, y_pred_rf))

# Matriz de confusão
conf_matrix = confusion_matrix(y_test, y_pred_rf)
print(conf_matrix)

"""A acurácia do modelo foi de 100%, e todas as previsões feitas foram para a classe 0 (não fraude).
Isso significa que o modelo não previu nenhuma fraude (classe 1). Ele classificou todas as transações como não fraudulentas (classe 0), o que é um sinal de que o modelo pode estar ignorando a classe minoritária (fraude). Isso é um problema, especialmente em cenários de detecção de fraude, onde o objetivo principal é identificar transações fraudulentas.
"""

train_accuracy = rf_classifier.score(X_train, y_train)
print(f'Acurácia no treino: {train_accuracy:.4f}')

test_accuracy = rf_classifier.score(X_test, y_test)
print(f'Acurácia no teste: {test_accuracy:.4f}')

train_sizes, train_scores, test_scores = learning_curve(rf_classifier, X_train, y_train, cv=5)

# Média e desvio padrão dos erros de treinamento e teste
train_mean = train_scores.mean(axis=1)
test_mean = test_scores.mean(axis=1)

plt.plot(train_sizes, train_mean, label='Erro de Treinamento')
plt.plot(train_sizes, test_mean, label='Erro de Teste')
plt.xlabel('Tamanho do Conjunto de Treinamento')
plt.ylabel('Erro')
plt.legend(loc='best')
plt.title('Curvas de Aprendizado')
plt.show()

# Oversampling da Classe Minoritária (Fraude)
# Aplicar SMOTE
smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X_train, y_train)

# Verificar o balanceamento das classes após SMOTE
print(f'Classes após SMOTE: {Counter(y_res)}')

# Treinar o modelo com os dados balanceados
rf_classifier = RandomForestClassifier(random_state=42, class_weight='balanced')
rf_classifier.fit(X_res, y_res)

# Avaliar o modelo
y_pred_rf = rf_classifier.predict(X_test)
print(classification_report(y_test, y_pred_rf))

"""**Avaliação com Métricas Apropriadas**  
Em problemas de desbalanceamento de classes, acurácia não é a melhor métrica. Em vez disso, foque em recall (capacidade de detectar fraudes) e F1-score (uma média harmônica entre precisão e recall).
"""

# Ajuste de hiperparâmetros
rf_classifier = RandomForestClassifier(
    n_estimators=200,  # Mais árvores
    max_depth=10,       # Limita a profundidade das árvores para evitar overfitting
    min_samples_split=5,  # Ajusta para uma divisão mais conservadora
    min_samples_leaf=2,  # Impede que as folhas fiquem com poucos exemplos
    random_state=42,
    class_weight='balanced'
)

# Treinar o modelo com SMOTE
rf_classifier.fit(X_res, y_res)

# Avaliar o modelo
y_pred_rf = rf_classifier.predict(X_test)
print(classification_report(y_test, y_pred_rf))

# Undersampling da Classe Maioritária
# Aplicar Undersampling
undersample = RandomUnderSampler(random_state=42)
X_res, y_res = undersample.fit_resample(X_train, y_train)

# Verificar o balanceamento das classes após Undersampling
print(f'Classes após Undersampling: {Counter(y_res)}')

# Treinar o modelo com os dados balanceados
rf_classifier = RandomForestClassifier(random_state=42, class_weight='balanced')
rf_classifier.fit(X_res, y_res)

# Avaliar o modelo
y_pred_rf = rf_classifier.predict(X_test)
print(classification_report(y_test, y_pred_rf))

"""#### Trabalhando com XGBoost"""

# Sparar as features (entradas) e a variável alvo (IsFraud):
X = df_processed.drop('IsFraud', axis=1)  # Features (variáveis independentes)
y = df_processed['IsFraud']  # Target (variável dependente)

# Dividir os dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Aplicar SMOTE para balancear as classes
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# Verificar a distribuição das classes após o SMOTE
print(f'Classes após SMOTE: {Counter(y_train_res)}')

# Criar o modelo XGBoost
xgb_classifier = xgb.XGBClassifier(
    scale_pos_weight=(len(y_train) - sum(y_train)) / sum(y_train),  # Ajusta para desbalanceamento
    random_state=42,
    eval_metric="logloss",  # Logloss é uma boa escolha para problemas desbalanceados
    use_label_encoder=False  # Desativa o aviso do label encoder
)

# Treinar o modelo
xgb_classifier.fit(X_train_res, y_train_res)

# Fazer previsões no conjunto de teste
y_pred = xgb_classifier.predict(X_test)

# Avaliar o modelo
print("Acurácia:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Exibir a matriz de confusão
conf_matrix = confusion_matrix(y_test, y_pred)
print("Matriz de Confusão:\n", conf_matrix)

# Definir os parâmetros para buscar
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.05, 0.1],
    'subsample': [0.8, 0.9, 1.0]
}

# Realizar a busca em grade
grid_search = GridSearchCV(estimator=xgb.XGBClassifier(random_state=42, use_label_encoder=False),
                           param_grid=param_grid,
                           scoring='roc_auc',  # Usar ROC-AUC como métrica
                           cv=3, n_jobs=-1, verbose=2)

# Ajustar o modelo
grid_search.fit(X_train_res, y_train_res)

# Melhor conjunto de parâmetros
print(f'Melhores parâmetros: {grid_search.best_params_}')

# Plotar a matriz de confusão
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=["Não Fraude", "Fraude"], yticklabels=["Não Fraude", "Fraude"])
plt.xlabel('Predição')
plt.ylabel('Real')
plt.title('Matriz de Confusão')
plt.show()

# Treinando o modelo com os melhores parâmetros encontrados
best_xgb_classifier = xgb.XGBClassifier(
    learning_rate=0.1,
    max_depth=5,
    n_estimators=300,
    subsample=0.9,
    scale_pos_weight=(len(y_train) - sum(y_train)) / sum(y_train),  # Ajuste para desbalanceamento
    random_state=42,
    use_label_encoder=False,
    eval_metric="logloss"  # Logloss é uma boa escolha para problemas desbalanceados
)

# Treinando o modelo
best_xgb_classifier.fit(X_train_res, y_train_res)

# Fazer previsões no conjunto de teste
y_pred_best = best_xgb_classifier.predict(X_test)

# Avaliar o modelo
print("Acurácia:", accuracy_score(y_test, y_pred_best))
print("Relatório de Classificação:\n", classification_report(y_test, y_pred_best))

# Exibir a matriz de confusão
conf_matrix = confusion_matrix(y_test, y_pred_best)
print("Matriz de Confusão:\n", conf_matrix)

# Plotar a matriz de confusão
import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=["Não Fraude", "Fraude"], yticklabels=["Não Fraude", "Fraude"])
plt.xlabel('Predição')
plt.ylabel('Real')
plt.title('Matriz de Confusão - Modelo XGBoost')
plt.show()

# Obter as probabilidades de cada classe
y_pred_prob = best_xgb_classifier.predict_proba(X_test)[:, 1]

# Ajustar o threshold
threshold = 0.2  # Por exemplo, estamos ajustando para 20% de probabilidade
y_pred_adjusted = (y_pred_prob > threshold).astype(int)

# Avaliar o modelo com o threshold ajustado
print("Acurácia:", accuracy_score(y_test, y_pred_adjusted))
print("Relatório de Classificação:\n", classification_report(y_test, y_pred_adjusted))

# Exibir a matriz de confusão
conf_matrix = confusion_matrix(y_test, y_pred_adjusted)
print("Matriz de Confusão:\n", conf_matrix)

# Verifique o recall e F1-score da classe 1
print("Recall para a classe 1 (fraude):", classification_report(y_test, y_pred_adjusted, target_names=["Não Fraude", "Fraude"]))

# Ajuste dinâmico do scale_pos_weight
scale_pos_weight = len(y_train_res) / (2 * sum(y_train_res == 1))
best_xgb_classifier = xgb.XGBClassifier(
    learning_rate=0.1,
    max_depth=5,
    n_estimators=300,
    subsample=0.9,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    use_label_encoder=False,
    eval_metric="logloss"
)

# Treinar novamente com o ajuste do scale_pos_weight
best_xgb_classifier.fit(X_train_res, y_train_res)

"""#### Trabalhando com classificação:"""

df_processed.head()

# Dividir os dados em conjuntos de treinamento e teste
X = df_processed.drop(columns=['IsFraud'])
y = df_processed['IsFraud']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from imblearn.over_sampling import RandomOverSampler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Criar o objeto RandomOverSampler
over_sampler = RandomOverSampler(random_state=42)

# Balancear o dataset de treinamento
X_train_balanced, y_train_balanced = over_sampler.fit_resample(X_train, y_train)

# Treinar o modelo de Random Forest com o dataset balanceado
rf_classifier = RandomForestClassifier(random_state=42)
rf_classifier.fit(X_train_balanced, y_train_balanced)

# Avaliar o modelo
rf_predictions = rf_classifier.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_predictions)

# Exibir os resultados
print("Acurácia do Random Forest:", rf_accuracy)
print("Relatório de Classificação do Random Forest:")
print(classification_report(y_test, rf_predictions))

print(f"Distribuição de classes em y_train antes do balanceamento: {Counter(y_train)}")
print(f"Distribuição de classes em y_train depois do balanceamento: {Counter(y_train_balanced)}")

from sklearn.model_selection import cross_val_score

# Usando validação cruzada
cross_val_scores = cross_val_score(rf_classifier, X_train_balanced, y_train_balanced, cv=5)
print(f"Acurácia média da validação cruzada: {cross_val_scores.mean()}")

rf_classifier = RandomForestClassifier(random_state=42, class_weight='balanced')
rf_classifier.fit(X_train_balanced, y_train_balanced)

from sklearn.metrics import f1_score, roc_auc_score

f1 = f1_score(y_test, rf_predictions, average='macro')  # F1-score macro (para todas as classes)
auc = roc_auc_score(y_test, rf_classifier.predict_proba(X_test), multi_class='ovr')  # AUC-ROC
print(f"F1-Score: {f1}")
print(f"AUC-ROC: {auc}")

# Treinar um modelo de Random Forest
rf_classifier = RandomForestClassifier(random_state=42)
rf_classifier.fit(X_train, y_train)

# Avaliar o modelo de Random Forest
rf_predictions = rf_classifier.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_predictions)
print("Acurácia do Random Forest:", rf_accuracy)
print("Relatório de Classificação do Random Forest:")
print(classification_report(y_test, rf_predictions))

# Treinar um modelo de Support Vector Machine (SVM)
svm_classifier = SVC(random_state=42)
svm_classifier.fit(X_train, y_train)

# Avaliar o modelo SVM
svm_predictions = svm_classifier.predict(X_test)
svm_accuracy = accuracy_score(y_test, svm_predictions)
print("\nAcurácia do SVM:", svm_accuracy)
print("Relatório de Classificação do SVM:")
print(classification_report(y_test, svm_predictions))

"""#### Trabalhando com o modelo de SENHOR Cássio:"""



"""### 5 - Avaliar o melhor modelo e sugerir melhorias"""