# -*- coding: utf-8 -*-
"""Processamento de dados com PySpark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t11FsztwhnhPoWLrcB22BogzuECFdMRu

Site para baixar a base de dados: http://dados.recife.pe.gov.br/dataset/situacao-final-dos-alunos-por-periodo-letivo/resource/9afdd9e1-9bc2-4d40-a070-4dec351d6e0f

Colab da professora: https://colab.research.google.com/drive/1wCnFJBdIEiu8I7Euc9PB4Iwax1aIpCxu?usp=sharing#scrollTo=QJqgy6lKfk2o
"""

"""
!wget -q !wget -q https://dlcdn.apache.org/spark/spark-3.4.1/spark-3.4.1-bin-hadoop3.tgz
!tar xf spark-3.4.1-bin-hadoop3.tgz
!pip install -q findspark
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!pip install pyspark
"""

import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.4.1-bin-hadoop3"
import findspark
findspark.init()
from pyspark.sql.functions import count, col, when
from pyspark.sql import functions as F
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pyspark.sql import SparkSession
sc = SparkSession.builder.master('local[*]').getOrCreate()

data = sc.read.csv("/content/situacaofinalalunos2022.csv", header = True, sep = ";", inferSchema=True)

df = data
df.show()

df.columns

df.dtypes

numero_de_linhas = df.count()

print(f'Número de linhas do DataFrame: {numero_de_linhas}')

df = df.withColumnRenamed('ano', 'Ano')
df = df.withColumnRenamed('nescolnome', 'Escola')
df = df.withColumnRenamed('ebairrnome', 'Bairro')
df = df.withColumnRenamed('eescolruae', 'Logradouro')
df = df.withColumnRenamed('aescolnume', 'Numero')
df = df.withColumnRenamed('cescolrpae', 'CodigoRegiao')
df = df.withColumnRenamed('modens', 'ModeloEnsino')
df = df.withColumnRenamed('anoensino', 'AnoEnsino')
df = df.withColumnRenamed('esermodesc', 'ModalidadeEnsino')
df = df.withColumnRenamed('nmodennome', 'NomeModalidadeEnsino')
df = df.withColumnRenamed('turma', 'Turma')
df = df.withColumnRenamed('nturesnome', 'Turno')
df = df.withColumnRenamed('mat', 'Matricula')
df = df.withColumnRenamed('alunosexo', 'Sexo')
df = df.withColumnRenamed('situ', 'Situacao')
df = df.withColumnRenamed('esitaldesc', 'SituacaoDescricao')

df.show(7, truncate=False)

for columns in df:
  print(df.select(columns).distinct().show())

sexo_3 = df.filter(col('Sexo') == 3).show(truncate=False)

modalidade_null = df.filter(col('ModalidadeEnsino').isNull()).show(truncate=False)

df_limpo = df.selectExpr("*")
df_limpo.show(truncate=False)

df_limpo = df_limpo.filter(col('Sexo') == 3).show(truncate=False)

df_limpo = df_limpo.filter(col('Sexo') != 3)
df_limpo.show(truncate=False)

df_limpo = df_limpo.filter(col('Sexo') == 3).show(truncate=False)

df_limpo = df.selectExpr("*").filter(col('ModalidadeEnsino').isNull())
df_limpo.show(truncate=False)

from pyspark.sql.functions import when

df_limpo = df.withColumn('ModalidadeEnsino', when(col('ModalidadeEnsino').isNull(), 'NAO INFORMADO').otherwise(col('ModalidadeEnsino')))

df_limpo.show(truncate=False)

modalidade_null = df_limpo.filter(col('ModalidadeEnsino').isNull()).show(truncate=False)

resultados_filtro = df_limpo.filter((col('NomeModalidadeEnsino') == 'ENSINO FUNDAMENTAL') & (col('SituacaoDescricao') == 'REPROV P/  FALTA')).show(truncate=False)

contagem = df_limpo.filter((col('NomeModalidadeEnsino') == 'ENSINO FUNDAMENTAL') & (col('SituacaoDescricao') == 'REPROV P/  FALTA')).count()

print(f"Número de linhas após o filtro: {contagem}")

contagem2 = df_limpo.filter((col('SituacaoDescricao') == 'REPROV P/  FALTA')).count()

print(f"Número de linhas após o filtro: {contagem2}")

"""Em torno de 252 alunos do ensino fundamental foram reprovados por falta no ano de 2022.
Se torna um número pequeno se compararmos a 97260, mas se percebemos que do total de reprovados (444), 252 corresponde a quase 57%. Se torna um pontinho de atenção aí.
"""

contagem3 = df_limpo.filter((col('SituacaoDescricao') == 'FALECIDO')).count()

print(f"Número de linhas após o filtro: {contagem3}")

"""## Processamento e Análise Descritiva Com Pandas"""

df_pandas = df_limpo.toPandas()

df_pandas

df_pandas.dtypes

# Importar matplotlib.
import matplotlib.pyplot as plt
# Importar seaborn.
import seaborn as sns

# Trocando os dados para números

df_pandas.loc[df_pandas['Situacao'] == 'RF', 'Situacao'] = '1'
df_pandas.loc[df_pandas['Situacao'] == 'RN', 'Situacao'] = '2'
df_pandas.loc[df_pandas['Situacao'] == 'MO', 'Situacao'] = '3'
df_pandas.loc[df_pandas['Situacao'] == 'RT', 'Situacao'] = '4'
df_pandas.loc[df_pandas['Situacao'] == 'FA', 'Situacao'] = '5'
df_pandas.loc[df_pandas['Situacao'] == 'AP', 'Situacao'] = '6'
df_pandas.loc[df_pandas['Situacao'] == 'D', 'Situacao'] = '7'
df_pandas.loc[df_pandas['Situacao'] == 'TA', 'Situacao'] = '8'
df_pandas.loc[df_pandas['Situacao'] == 'TR', 'Situacao'] = '9'

# Convertendo a coluna para inteiro para coseguir fazer gráficos
df_pandas['Situacao'] = df_pandas['Situacao'].astype(int)

"""### LEGENDA DA TROCA:

1 - RF - REPROV P/ FALTA  
2 - RN - RENV S/SIT FINAL DEF - Remanejado sem situação final definida.  
3 - MO - REMANEJADO  
4 - RT - RETIDO  
5 - FA - FALECIDO  
6 - AP - APROVADO  
7 - D - DESIST/DEIXOU FREQUE   
8 - TA - TR DUR ANO FORA REDE - Transferido durante o ano, fora da rede de ensino.  
9 -TR - TR DUR ANO P/REDE - Transferido durante o ano para a rede de ensino.  
"""

histograma = df_pandas.groupby(['CodigoRegiao', 'Situacao']).size().unstack()

histograma.plot(kind='bar', stacked=True)

plt.xlabel('Região')
plt.ylabel('Quantidade')
plt.title('Histograma de Situação por Região')

plt.show()

plt.boxplot(df_pandas.Situacao)
plt.show()

# O resultado mais comum é o 6 que significa aprovado. Por isso todos os outros estão meio que "fora" do padrão

# Plotando dispersão de dados = relacionando duas variáveis numéricas.
plt.figure(figsize = (7,4))
plt.scatter(
    df_pandas['Situacao'],
    df_pandas['CodigoRegiao'],
    color='purple')

plt.xlabel("Situacao")
plt.ylabel("CodigoRegiao")
plt.show()

# Esse gráfico ficou horroroso, mas foi engraçado fazer
plt.rcParams["figure.figsize"] = (15, 8)
plt.plot (df_pandas['Situacao'], df_pandas['CodigoRegiao'], color = 'purple', marker = 'o')

plt.title('Gráfico de Situação por Região',  fontsize = 25, color = 'darkblue')

plt.xlabel('Situação Escolar', fontsize = 20, color = 'darkblue')
plt.ylabel('Código Regiao',  fontsize = 20, color = 'darkblue')

plt.legend(['Número de Alunos'], loc = 'best', fontsize = 15)

# Eu não tinha muito dado que poderia ser tranformado em numérico, sorry.

# That's all folks - Sara Lopes