# -*- coding: utf-8 -*-
"""Projeto de Chatbot para Anotação de Pedidos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vo-uJxGPdxdArsWp32YP27jTdGpFHjoQ

# Projeto de Chatbot para Anotação de Pedidos da Pizzaria Delícia 🍕😋

## Integrantes do **Grupo 05**:

- Gustavo Pereira Tramontin
  - Sara Rayane Araujo Lopes
  - Isadora dos Santos Magalhães
  - Noele Natalia Miranda Rodrigues
  - Thaísa Silva Lopes

## Orientações sobre o projeto:

### Entrega do projeto:

- O projeto deve ser realizado em grupo. Os grupos estão separados em arquivos com os nomes dos participantes. Os arquivos podem ser encontrados dentro do Drive Compartilhado da plataforma LMS.
- Informações sobre a entrega:
    - Prazo até o dia 27/10/2023 às 23:59
    - A entrega deverá ser via plataforma LMS, no menu Projeto
    - Formatos aceitos:
        - Códigos python .py ou .ipynb com comentários claros de cada funcionalidade
        - Arquivo .zip com códigos .py ou .ipynb com README.md explicando como executar o código
        - Link do Github com acesso público ou liberado para o professor

### Apresentação do Projeto:

Neste projeto, os alunos terão a oportunidade de aplicar conceitos fundamentais de programação em Python, como variáveis, estruturas condicionais, estruturas de repetição, listas e funções, criando um chatbot simples para anotar pedidos de uma pizzaria. Este é um exercício prático e envolvente que permitirá aos alunos desenvolver habilidades essenciais de programação e lógica.

### Descrição do Projeto:

Imagine que você está criando um chatbot para a Pizzaria que Delícia, onde o funcionamento da pizzaria é de 17h às 3h da manhã. Os clientes podem fazer pedidos de pizzas disponíveis. O chatbot interagirá com os clientes, perguntando o sabor da pizza desejada e confirmará o preço, caso a pizza escolhida esteja no menu. O chatbot também será capaz de lidar com pedidos de múltiplas pizzas, calcular o valor total do pedido e fornecer uma lista final de pizzas pedidas e o valor total.

### Instruções para os Alunos:

#### **DADOS INICIAIS:**

#### *Carregue o menu abaixo em uma lista*
<center>
Menu com pizzas disponíveis:

| Nome da pizza | Preço |
| ------------- | ----- |
| Calabresa     | 70 |
| Queijo        | 50 |
| Pepperoni     | 80 |
| Margherita    | 80 |
| Vegetariana   | 80 |

</center>
<br>

#### *Parâmetro para inciar simular a hora do atendimento*

```python
import random
#horário de funcionamento entre 17 às 03h
hora = random.randint(1,24)
```

### FLUXO PRINCIPAL

#### Atendimento
    - Incie o atendimento ao cliente com uma mensagem de boas vindas.
      - A saudação deverá respeitar a seguinte regra:
          - Quando a hora for menor que 18 - Boa tarde
          - Quando a hora estiver entre 18 e 23 (ambos inclusive) - Boa noite
          - Quando a hora estiver entre 0 e 3 (ambos inclusive) - Bom dia
      - Use o código que está na sessão DADOS INCIAIS para gerar a hora.
    - Após a mensagem de boas vindas apresente o menu de atendimento, que deve ter 2 opções
        - Visualizar Menu
        - Fazer Pedido

#### Visualizar Menu
    - Ao selecionar essa opção o menu deve ser apresentado ao usuário de modo amigável e de fácil leitura
    - A apresentação do menu de vir seguida de uma mensagem perguntando ao usuário se ele já escolheu a pizza, dando duas opções de resposta, sendo uma para iniciar o pedido e outra para sair do chat.

#### Pedidos
    - Inicie o pedido perguntando os dados do cliente
      - Nome do cliente
      - Endereço do cliente
      - Forma de pagamento (Dinheiro, Cartão ou Pix)
    - Em seguida receba o pedido do cliente
    - Verifique se a pizza escolhida está disponível no menu.
        - Caso verdadeiro, confirme o preço da pizza.
        - Caso falso, informe que não está no menu e peça que escolha outra opção
    - Continue perguntando ao cliente se deseja fazer outro pedido.
    - Quando o cliente não quiser fazer mais pedidos, encerre o loop.
    - Ao final do pedido, exiba um resumo com as pizzas pedidas e o valor total do pedido. Use os dados do cliente para ter uma interação maior.

### Conclusão:

Este projeto oferece aos alunos a oportunidade de aplicar conceitos fundamentais de programação de uma maneira prática e divertida. Eles podem aprimorar o código, adicionar recursos adicionais, como a opção de bebidas, expandir o menu de pizzas ou integrar o chatbot a um sistema de pedidos em um restaurante real.

### Bônus:

As atividades bônus é oferecida apenas para estimular mais o seu desenvolvimento no projeto, não se preocupe caso não consiga entrega-la. O principal é a proposta acima!!

- Em um chatbot a comunicação deve ser o mais humana possível, faça o uso de mensagens para tornar o fluxo fácil de ser entendido, tornando a experiência do usuário objetia e prazerosa.
- Melhore o menu com mais opções e de tamanhos de pizza
- Identifique e comente no final do seu código onde existe a oportunidade de uso de funções

## Código Inicial:
"""

## REGISTRO DE INFORMAÇÕES PADRÃO ##
## Aqui o dono da pizzaria registra os sabores disponíveis e valores de cada sabor (não atualiza o menu automaticamente)

#Sabores
sabores = ["CALABRESA", "QUEIJO","PEPPERONI","MARGHERITA","VEGETARIANA"]

#Preços
p_calab = 70.00
p_quei= 50.00
p_peppe = 80.00
p_marg = 80.00
p_veg = 80.00

#Listas
lista_pedido = []
lista_pagar = []

#INÍCIO DO BOT

## OPERAÇÃO APÓS RECEBER MENSAGEM DO CLIENTE ##

import random
hora = random.randint(1,24) # horário de funcionamento entre 17 às 03h
print("Início da conversa: " ,hora, "horas.")

if hora >= 17 or hora < 3: #Condição para que o restaurante esteja aberto e saudações por horário de início da conversa
  print("\n### ESTAMOS ABERTOS ###")

  if 18 > hora >= 17: # Quando a hora for menor que 18 - Boa tarde
      print("\nBoa tarde! - Seja bem vind@ ao ChatBot da Pizzaria que Delícia!\n\nSelecione uma das opções abaixo digitanto o texto informado entre parenteses para prosseguir: ")

  elif 23 >= hora >= 18: # Quando a hora estiver entre 18 e 23 (ambos inclusive) - Boa noite
      print("\nBoa noite! - Seja bem vind@ ao ChatBot da Pizzaria que Delícia!\n\nSelecione uma das opções abaixo digitanto o texto informado entre parenteses para prosseguir: ")

  elif hora > 23 or hora <= 3: # Quando a hora estiver entre 0 e 3 (ambos inclusive) - Bom dia
      print("\nBom dia! - Seja bem vind@ ao ChatBot da Pizzaria que Delícia!\n\nSelecione uma das opções abaixo digitanto o texto informado entre parenteses para prosseguir: ")

  print("\n############################")
  print("#  Visualizar menu (MENU)  #")
  print("#  Fazer pedido (PEDIDO)   #")
  print("############################")
  entrada_inicial = input("\nO que deseja fazer? ").upper() #Entrada para MENU ou PEDIDO

  while entrada_inicial != "MENU" and entrada_inicial != "PEDIDO": #Validação da entrada para MENU ou PEDIDO
    entrada_inicial = input("Ah, comando inválido! Digite MENU ou PEDIDO para seguir: ").upper()
  if entrada_inicial == "MENU" : #Selecionou MENU na opção inicial
      print("\nEsse é o nosso menu de pizzas!")
      print("\n| SABOR DA PIZZA  | PREÇO       |")
      print("| --------------- | ---------   |")
      print("| Calabresa       | R$ 70.00    |")
      print("| Queijo          | R$ 50.00    |")
      print("| Pepperoni       | R$ 80.00    |")
      print("| Margherita      | R$ 80.00    |")
      print("| Vegetariana     | R$ 80.00    |")

      saida_menu = input("\nGostaria de realizar seu pedido? (S/N): ").upper() #Realiza a pergunta para pedir ou acabar com a conversa!

  while saida_menu != "S" and saida_menu != "N": #Validação da resposta após ver o MENU (S/N)
      saida_menu = input("Ah, comando inválido! Gostaria de realizar seu pedido? (S/N): ").upper()
  if saida_menu == "N" : #Cliente desistiu da compra após ver o menu
    print("Ah, que pena! Quem sabe da próxima vez, hein!?")
    pass #Passa as partes de PEDIDO e PRECO
  pass #Passa a mensagem de FECHADO


## INICIANDO O PEDIDO ##

  if saida_menu == "S" or entrada_inicial == "PEDIDO": #Selecionou PEDIDO na opção inicial sem ver o menu
    print("\n#### Ótimo! Vamos iniciar seu pedido! ####")
    nome_cliente = input("Insira seu nome: ").title() #Title para arrumar o nome
    end_cliente = input("Insira o endereço para entrega: ").title()
    pagamento_cliente = input("Qual a forma de pagamento? (Dinheiro, Cartão ou Pix): ").title()

    pedido = input("\nDigite o sabor da pizza desejada: ").upper() #Input do sabor da pizza (repetição da entrada)

    if pedido == "CALABRESA": #Informa qual sabor foi adicionado ao pedido e o valor
      print("Adicionado Pizza Calabresa ao pedido - Valor R$ 70.00")
    elif pedido == "QUEIJO":
      print("Adicionado Pizza Queijo ao pedido - Valor R$ 50.00")
    elif pedido == "PEPPERONI":
      print("Adicionado Pizza Pepperoni ao pedido - Valor R$ 80.00")
    elif pedido == "MARGHERITA":
      print("Adicionado Pizza Margherita ao pedido - Valor R$ 80.00")
    elif pedido == "VEGETARIANA":
      print("Adicionado Pizza Vegetariana ao pedido - Valor R$ 80.00")
    while pedido != "FINALIZAR":
        if pedido not in sabores: #Validação do sabor solicitado (se há no menu)
              pedido = input("\nAh, esse sabor não existe! Tente novamente ou digite FINALIZAR para encerrar: ").upper() #Se não possuir no menu, TENTE NOVAMENTE
        else:
              lista_pedido.append(pedido) #Se possuir o sabor no MENU, entra na lista_pedido para posterior análise de preço
              pedido = input("\nGostaria de adicionar alguma outra pizza ao pedido? Se não digite FINALIZAR: ").upper() #Refaz a pergunta para continuar pedindo ou encerrar

        if pedido == "CALABRESA": #Informa qual sabor foi adicionado ao pedido e o valor
              print("Adicionado Pizza Calabresa ao pedido - Valor R$ 70.00")
        elif pedido == "QUEIJO":
              print("Adicionado Pizza Queijo ao pedido - Valor R$ 50.00")
        elif pedido == "PEPPERONI":
              print("Adicionado Pizza Pepperoni ao pedido - Valor R$ 80.00")
        elif pedido == "MARGHERITA":
              print("Adicionado Pizza Margherita ao pedido - Valor R$ 80.00")
        elif pedido == "VEGETARIANA":
              print("Adicionado Pizza Vegetariana ao pedido - Valor R$ 80.00")

## CÁLCULO DE PREÇO ##

    total_pagar = 0

    for i in lista_pedido: #Adiciona o valor de cada pizza conforme SABOR inserido na LISTA_PEDIDO e valor de cada sabor informado no registro (primeiras linhas)
      if i == "CALABRESA":
        total_pagar = total_pagar + p_calab
        lista_pagar.append(total_pagar)
        continue
      if i == "QUEIJO":
        total_pagar = total_pagar + p_quei
        lista_pagar.append(total_pagar)
        continue
      if i == "PEPPERONI":
        total_pagar = total_pagar + p_peppe
        lista_pagar.append(total_pagar)
        continue
      if i == "MARGHERITA":
        total_pagar = total_pagar + p_marg
        lista_pagar.append(total_pagar)
        continue
      if i == "VEGETARIANA":
        total_pagar = total_pagar + p_veg
        lista_pagar.append(total_pagar)
        continue

    print("\n##### SEU PEDIDO FOI CONFIRMADO! #####") #Mensagem de fechamento do pedido
    print(f"\nAgradeçemos a sua preferência, {nome_cliente}!")
    print(f"O pedido será entregue no endereço {end_cliente}!")
    print(f"A forma de pagamento escolhida foi {pagamento_cliente}!")
    print("\nSegue a lista das pizzas pedidas: ")

    contador = 1 #Contador para enumerar as pizzas inicianco em 1
    for elemento in range(len(lista_pedido)):
      print(contador,"-", lista_pedido[elemento])
      contador += 1

    print("\nO valor total da compra foi de: R$", round(total_pagar,2))

else:
  print("\nAh, infelizmente estamos fechados no momento!")
  print("\nEntre em contato conosco entre 17h e 03h e garanta a melhor pizza da cidade! \nAté mais!")

"""## Código com Melhorias:

### Funções:
"""

#FUNÇÃO PARA CRIAR A LISTA DE PIZZAS DO PEDIDO

def fun_sabores(pedido):

    while pedido != "FINALIZAR":
        if pedido not in sabores: #Validação do sabor solicitado (se há no menu)
              pedido = input("\nAh, esse sabor não existe! Tente novamente ou digite FINALIZAR para encerrar: ").upper() #Se não possuir no menu, TENTE NOVAMENTE
        else:
              lista_pedido.append(pedido) #Se possuir o sabor no MENU, entra na lista_pedido para posterior análise de preço
              if pedido == "CALABRESA": #Informa qual sabor foi adicionado ao pedido e o valor
                print("Adicionado Pizza Calabresa ao pedido - Valor R$ 70.00")
              elif pedido == "QUEIJO":
                print("Adicionado Pizza Queijo ao pedido - Valor R$ 50.00")
              elif pedido == "PEPPERONI":
                print("Adicionado Pizza Pepperoni ao pedido - Valor R$ 80.00")
              elif pedido == "MARGHERITA":
                print("Adicionado Pizza Margherita ao pedido - Valor R$ 80.00")
              elif pedido == "VEGETARIANA":
                print("Adicionado Pizza Vegetariana ao pedido - Valor R$ 80.00")
              elif pedido == "FRANGO COM CHEDDAR":
                print("Adicionado Pizza Frango com Cheddar ao pedido - Valor R$ 120.00")
              elif pedido == "QUATRO QUEIJOS":
                print("Adicionado Pizza Quatro Queijos ao pedido - Valor R$ 200.00")
              elif pedido == "ROMEU E JULIETA":
                print("Adicionado Pizza Romeu e Julieta ao pedido - Valor R$ 100.00")
              elif pedido == "CHOCOLATE":
                print("Adicionado Pizza Chocolate ao pedido - Valor R$ 50.00")
        pedido = input("\nGostaria de adicionar alguma outra pizza ao pedido? Se não digite FINALIZAR: ").upper() #Refaz a pergunta para continuar pedindo ou encerrar

    return lista_pedido

#FUNÇÃO PARA CALCULO DO PREÇO TOTAL

def valor_pedido(lista_pedido):
    total_pagar = 0

    for i in lista_pedido: #Adiciona o valor de cada pizza conforme SABOR inserido na LISTA_PEDIDO e valor de cada sabor informado no registro (primeiras linhas)
      if i == "CALABRESA":
        total_pagar += p_calab
        lista_pagar.append(total_pagar)
        continue
      if i == "QUEIJO":
        total_pagar += p_quei
        lista_pagar.append(total_pagar)
        continue
      if i == "PEPPERONI":
        total_pagar += p_peppe
        lista_pagar.append(total_pagar)
        continue
      if i == "MARGHERITA":
        total_pagar += p_marg
        lista_pagar.append(total_pagar)
        continue
      if i == "VEGETARIANA":
        total_pagar += p_veg
        lista_pagar.append(total_pagar)
        continue
      if i == "FRANGO COM CHEDDAR":
        total_pagar += p_frango
        lista_pagar.append(total_pagar)
        continue
      if i == "QUATRO QUEIJOS":
        total_pagar += p_quat
        lista_pagar.append(total_pagar)
        continue
      if i == "ROMEU E JULIETA":
        total_pagar += p_rom
        lista_pagar.append(total_pagar)
        continue
      if i == "CHOCOLATE":
        total_pagar += p_choc
        lista_pagar.append(total_pagar)
        continue

    return lista_pagar

"""### Menu com mais Opções de Sabores:"""

## REGISTRO DE INFORMAÇÕES PADRÃO COM FUNÇÕES ##

## Aqui o dono da pizzaria registra os sabores disponíveis e valores de cada sabor (não atualiza o menu automaticamente)

#Sabores
sabores = ["CALABRESA", "QUEIJO","PEPPERONI","MARGHERITA","VEGETARIANA", "FRANGO COM CHEDDAR", "QUATRO QUEIJOS", "ROMEU E JULIETA", "CHOCOLATE"] # Adicionado novos sabores

#Preços
p_calab = 70.00
p_quei= 50.00
p_peppe = 80.00
p_marg = 80.00
p_veg = 80.00
p_frango = 120.00
p_quat = 200.00
p_rom = 100.00
p_choc = 50.00


#Listas
lista_pedido = []
lista_pagar = []


#def precos

#INÍCIO DO BOT

## OPERAÇÃO APÓS RECEBER MENSAGEM DO CLIENTE ##

import random
hora = random.randint(1,24) # horário de funcionamento entre 17 às 03h
print("Início da conversa: " ,hora, "horas.")

if hora >= 17 or hora < 3: #Condição para que o resteurante esteja aberto e saudações por horário de início da conversa
  print("\n### ESTAMOS ABERTOS ###")

  if 18 > hora >= 17: # Quando a hora for menor que 18 - Boa tarde
      print("\nBoa tarde! - Seja bem vind@ ao ChatBot da Pizzaria que Delícia!\n\nSelecione uma das opções abaixo digitanto o texto informado entre parenteses para prosseguir: ")

  elif 23 >= hora >= 18: # Quando a hora estiver entre 18 e 23 (ambos inclusive) - Boa noite
      print("\nBoa noite! - Seja bem vind@ ao ChatBot da Pizzaria que Delícia!\n\nSelecione uma das opções abaixo digitanto o texto informado entre parenteses para prosseguir: ")

  elif hora > 23 or hora <= 3: # Quando a hora estiver entre 0 e 3 (ambos inclusive) - Bom dia
      print("\nBom dia! - Seja bem vind@ ao ChatBot da Pizzaria que Delícia!\n\nSelecione uma das opções abaixo digitanto o texto informado entre parenteses para prosseguir: ")

  print("\n############################")
  print("#  Visualizar menu (MENU)  #")
  print("#  Fazer pedido (PEDIDO)   #")
  print("############################")
  entrada_inicial = input("\nO que deseja fazer? ").upper() #Entrada para MENU ou PEDIDO

  while entrada_inicial != "MENU" and entrada_inicial != "PEDIDO": #Validação da entrada para MENU ou PEDIDO
    entrada_inicial = input("Ah, comando inválido! Digite MENU ou PEDIDO para seguir: ").upper()
  if entrada_inicial == "MENU" : #Selecionou MENU na opção inicial
      print("\nEsse é o nosso menu de pizzas!")
      print("\n| SABOR DA PIZZA      | PREÇO       |")
      print("| ------------------  | ---------   |")
      print("| Calabresa           | R$ 70.00    |")
      print("| Queijo              | R$ 50.00    |")
      print("| Pepperoni           | R$ 80.00    |")
      print("| Margherita          | R$ 80.00    |")
      print("| Vegetariana         | R$ 80.00    |")
      print("| Frango com Cheddar  | R$ 120.00   |")
      print("| Quatro Queijos      | R$ 200.00   |")
      print("| Romeu e Julieta     | R$ 100.00   |")
      print("| Chocolate           | R$ 50.00    |")

      saida_menu = input("\nGostaria de realizar seu pedido? (S/N): ").upper() #Realiza a pergunta para pedir ou acabar com a conversa!

  while saida_menu != "S" and saida_menu != "N": #Validação da resposta após ver o MENU (S/N)
      saida_menu = input("Ah, comando inválido! Gostaria de realizar seu pedido? (S/N): ").upper()
  if saida_menu == "N" : #Cliente desistiu da compra após ver o menu
    print("Ah, que pena! Quem sabe da próxima vez, hein!?")
    pass #Passa as partes de PEDIDO e PRECO
  pass #Passa a mensagem de FECHADO


## INICIANDO O PEDIDO ##

  if saida_menu == "S" or entrada_inicial == "PEDIDO": #Selecionou PEDIDO na opção inicial sem ver o menu
    print("\n#### Ótimo! Vamos iniciar seu pedido! ####")
    nome_cliente = input("Insira seu nome: ").title() #Title para arrumar o nome
    end_cliente = input("Insira o endereço para entrega: ").title()
    pagamento_cliente = input("Qual a forma de pagamento? (Dinheiro, Cartão ou Pix): ").upper()

    while pagamento_cliente != "DINHEIRO" and pagamento_cliente != "CARTÃO" and pagamento_cliente != "CARTAO" and pagamento_cliente != "PIX": #Validação de método de pagamento
      pagamento_cliente = input("Ah, pagamento inválido! Insira \"DINHEIRO\", \"CARTÃO\" ou \"PIX\"").upper()

    pedido = input("\nDigite o sabor da pizza desejada: ").upper() #Input do sabor da pizza (repetição da entrada)
    fun_sabores(pedido) #Uso de função para criação da lista_pedido ------------------------------------------------------------->

## CÁLCULO DE PREÇO ##

    valor_pedido(lista_pedido) #Uso de função para calculo do valor total do pedido ------------------------------------------------------------->

    print("\n##### SEU PEDIDO FOI CONFIRMADO! #####") #Mensagem de fechamento do pedido
    print(f"\nAgradeçemos a sua preferência, {nome_cliente}!")
    print(f"O pedido será entregue no endereço {end_cliente}!")
    print(f"A forma de pagamento escolhida foi {pagamento_cliente}!")
    print("\nSegue a lista das pizzas pedidas: ")

    contador = 1 #Contador para enumerar as pizzas inicianco em 1
    for elemento in range(len(lista_pedido)):
      print(contador,"-", lista_pedido[elemento])
      contador += 1

    print("\nO valor total da compra foi de: R$", lista_pagar[-1])

else:
  print("\nAh, infelizmente estamos fechanos no momento!")
  print("\nEntre em contato conosco entre 17h e 03h e garanta a melhor pizza da cidade! \nAté mais!")

"""### Conclusões Finais:

Concluindo, na versão 2 do código do projeto, realizamos melhorias importantes:
-  Expandimos o menu de sabores de pizza
-  Implementamos funções para estruturar o código
- Validamos métodos de pagamento
- Incluímos comentários para tornar o código mais claro.

Isso resultou em um programa mais completo e organizado, capaz de lidar com várias opções de pizza, oferecendo uma experiência aprimorada aos clientes. No entanto, ainda há espaço para simplificar o código, incluir novas funções, automatizar atualizações do menu e valores, evitar redundância de código (duplicidade) e aprimorar mensagens informativas.
"""