# -*- coding: utf-8 -*-
"""Projeto de Análise de Satisfação de Clientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_Frb8nfEZUUvb_xKLdgluBvrhNC9buh

**Lista de itens/dicas utilizados no projeto**

1) Leitura de arquivo com dados.

2) Quantidade de linhas de colunas

3) Visualização de dados utilizando Matplotlib

4) Encontrar maior/menores valores

5) Agrupamento
"""

# importando as bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#from google.colab import drive
#drive.mount('/content/drive')

#1) Leitura de arquivo com dados
dt = pd.read_csv('amostra_clientes.csv')

from google.colab import drive
drive.mount('/content/drive')

dt.head(4)

#Verificando quantidade de linhas e de colunas do dataset
print(f'O seu dataset tem {dt.shape[0]} linhas e {dt.shape[1]} colunas')

# Detectando quantos valores nulos tem no dataset
dt.isnull().sum()

# Deletando NULL values do dataset
dt.dropna(inplace=True)

# Confirmando que valores Nulos foram deletados
dt.isnull().sum()

"""#### Conhecendo a amostra e nossos passageiros!"""

#Quantos homens e mulheres?
qty_male = dt['Gender'].value_counts()['Male']
qty_female = dt['Gender'].value_counts()['Female']

#Qual a média de idade e a faixa etária dessa amostra?
media_idade = dt['Age'].mean()
under_18 = (dt['Age']<18).sum()
under_30 = ((dt['Age']>=18) & (dt['Age']<30)).sum()
under_50 = ((dt['Age']>=30) & (dt['Age']<50)).sum()
upper_50 = (dt['Age']>=50).sum()

#Quantos são passageiros recorrente (fiel) e quantos não são?
loyal_pass = dt['Customer Type'].value_counts()['Loyal Customer']
disloyal_pass = dt['Customer Type'].value_counts()['disloyal Customer']

#Quantos passageiros andam em cada classe?
bus_class = dt['Class'].value_counts()['Business']
eco_class = dt['Class'].value_counts()['Eco']
eco_plus = dt['Class'].value_counts()['Eco Plus']

#Qual é o tipo de viagem que o nosso cliente costuma fazer? Pessoal ou a negócios?
business_travel = dt['Type of Travel'].value_counts()['Business travel']
personal_travel =  dt['Type of Travel'].value_counts()['Personal Travel']

#REPORT (perfil do usuário do serviço)

print("RELATÓRIO")
print("\nSabemos que a amostra conta com", dt.shape[0], "respostas de clientes da companhia aérea!")
print("\nDesse total,", qty_male, "são homens e",qty_female,"são mulheres.")
print("\nNessa amostra encontramos uma média de idade de",round(media_idade),"anos, composto por:\n-", under_18,"passageiros com menos de 18 anos;\n-", under_30,"passageiros entre 18 e 30 anos;\n-", under_50,"passageiros entre 30 e 50 anos;\n-", upper_50,"passageiros com mais de 50 anos.")
print("\nEntre todos os passageiros,", loyal_pass,"são passageiros leais/recorrentes e", disloyal_pass,"não são.")
print("\nSeparando por classe de viagem:\n-",bus_class,"passageiros viajam na Business;\n-",eco_plus,"passageiros viajam na Eco Plus;\n-",eco_class,"passageiros viajam na Eco.")
print("\nDividindo por tipo de viagem: \n-",business_travel, "passageiros viajam a negócios;\n-",personal_travel, "passageiros fazem viagens pessoais.")

"""#### Analisando as respostas da avaliação (notas de 0 a 5) sobre a satisfação dos clientes"""

#Verificando a média de cada categoria avaliada
media_notas = round(dt.mean(numeric_only=True),2).to_frame()
media_notas

#Separando as categorias de satisfação da amostra:
satisfaction = media_notas <= 5
satisfaction_categories = media_notas[satisfaction]
print('As categorias de satisfação do cliente são:')
satisfaction_categories.dropna()

#Considerando que abaixo de 3 a nota seja ruim, vamos separar os aspectos que podem representar fraquezas da empresa ou pontos que podem melhorar:
aspectos_negativos = media_notas < 3
negativos = media_notas[aspectos_negativos]
print('Os aspectos avaliados pelos passageiros como negativos da companhia são:')
negativos.dropna()

#Quem são os clientes que votaram abaixo de 3 para o pior item avaliado?
classe_internet = dt[dt['Inflight wifi service'] < 3].groupby(['Class', 'Type of Travel']).size().to_frame(name='Reclamações')
print("Os viajantes a trabalho da classe Business tiveram um nível de reclamação superior a qualquer outra classe e/ou tipo de viajante.\
\nNesse caso é importante que a empresa melhore sua disponibilidade de internet com o objeitivo de manter a fidelidade dos passageiros, uma vez que o valor das passagens são elevados.")
classe_internet

#Em que classe os consumidores são mais fieis?
dt1 = dt.groupby(['Class', 'Customer Type']).size().to_frame('Total Customers')
dt1['Percentage'] = ((dt1['Total Customers'] /
                  dt1['Total Customers'].sum()) * 100).round(1)
dt1

# 2) Visualização de dados utilizando Matplotlib

fidelidade_classe = dt.groupby(['Class', 'Customer Type']).size().reset_index(name='Count')
ax = fidelidade_classe.pivot(index='Class', columns='Customer Type', values='Count').plot(kind='barh', stacked=True)


plt.xlabel('Número de passageiros')
plt.ylabel('Classe de Viagem')
plt.title('Relação Lealdade por Classe de viagem')
plt.legend(title='Customer Type', bbox_to_anchor=(1, 1))
plt.show()

#Como o grau de satisfação dos passageiros está relacionada com a fidelidade?
dt.groupby(['Class', 'Customer Type', 'satisfaction']).size().to_frame()

#Qual a distribuição do grau de satisfação dos passageiros por classe?
dt.groupby(['Class', 'satisfaction']).size().to_frame()

# 2) Visualização de dados utilizando Matplotlib

#O grau de satisfação está relacionado com o tipo de viagem?
#Quem stá mais insatisfeito: quem viaja a trabalho ou para fins pessoais?
cores_personalizadas = ['red', 'green']
tipo_viagem = dt.groupby(['Type of Travel', 'satisfaction']).size().reset_index(name='Count')

bx = tipo_viagem.pivot(index='Type of Travel', columns='satisfaction', values='Count').plot(kind='barh', stacked=True, color=cores_personalizadas)


plt.xlabel('Número de passageiros')
plt.ylabel('Tipo de Viagem')
plt.title('Relação Tipo de Viagem e Satisfação do Cliente')
plt.legend(title='Customer Type', bbox_to_anchor=(1, 1))
plt.show()



#3) Encontrar maior/menores valores
#O grau de satisfação está relacionado ao atraso do voo, tanto na saída quanto na chegada? Se sim, há um tempo máximo suportado pelos clientes para o voo atrasar?
dt.groupby(['Class', 'satisfaction']).agg({
      'Departure Delay in Minutes' : ['mean', np.max],
      'Arrival Delay in Minutes' : ['mean', np.max]
  })